"""Single source of truth for the application version."""
__version__ = "0.2.0"
__app_name__ = "fzBGPTools"
__app_id__ = "fzbgptools"
__description__ = "Network Peering Mapper — BGP, hosts, diagnósticos e descoberta."
__author__ = "Eng. Roger Luft"
__author_email__ = "roger@webstorage.com.br"
__company__ = "Webstorage Tecnologia"
__url__ = "https://github.com/rluft/fzBGPTools"
__update_url__ = "https://fzrepo.rogerluft.com.br"
__license__ = "CC-BY-4.0"
__copyright__ = "© 2025-2026 Webstorage Tecnologia"
